
//Cart and Wishlist Functionality
export const MODIFY_ITEM_SIZE = "MODIFY_ITEM_SIZE";
export const MODIFY_ITEM_QUANTITY = "MODIFY_ITEM_QUANTITY";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const MAKE_CART_EMPTY = "MAKE_CART_EMPTY";

export const REMOVE_WISHLIST_ITEM = "REMOVE_WISHLIST_ITEM";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";

export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
